project_id = "jokzpcijyyaymsbvxcrk"

[functions.send-contact-email]
verify_jwt = false

[functions.chat-bot]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.seed-knowledge]
verify_jwt = false

[functions.chat-bot]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.seed-knowledge]
verify_jwt = false